### ISSUE TITLE
Shard

### ISSUE THREAD

**Issue by thebigwolfy** [Androz2091/discord-giveaways#109]
Salut, j'ai un problème avec les shards. J'ai mis exactement le code indiquée dans la documentation : le giveaway se lance bien mais y'a deux fois le/les winner(s)

**Comment by NicoHd105** [comment]
Cela se produit-il pour chaque cadeau ou juste parfois? Et utilisez-vous la dernière version du module?

**Comment by NicoHd105** [comment]
_I hope you understand english_
So you mean that it sends 2 win messages for the same giveaway?
If that is the case then the sharding isn't even the issue, but don't worry v.4.3.0 of this module/package which is currently a pr will fix this issue.

If I guessed right then please close this issue otherwise correct my statement and maybe provide a more detailed description.

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released!
