### ISSUE TITLE
Ended Raffle Error Appearing Unfinished

### ISSUE THREAD

**Issue by Veltimo** [Androz2091/discord-giveaways#131]
There is one raffle and it seems unfinished even though this raffle is over, and the bot does not show the winners. Thinking the raffle was not over, I used the terminate command, but when I looked at the console, I realized that the raffle was already over, but the bot did not update its message and did not say the winners. What should I do to prevent problems from happening in this way?

![NfIZjNyXHn](https://user-images.githubusercontent.com/67333585/101678590-32068100-3a6f-11eb-9db2-bcbb1381ded2.png)
![opera_5qx1CSeArD](https://user-images.githubusercontent.com/67333585/101678648-49de0500-3a6f-11eb-8032-8b227192aa27.png)

**Comment by NicoHd105** [comment]
Has this happend only once or multiple times?

**Comment by Veltimo** [comment]
It only happened once, and it's the first time I've seen

**Comment by NicoHd105** [comment]
Are you using a custom DB?

**Comment by Veltimo** [comment]
no

**Comment by NicoHd105** [comment]
Weird, I only had sucht things when my giveaway data got deleted after a restart 😆 but ypu still got a log.
It does have all the permissions for that channel that it needs though?
If yes then I guess we just have to say it was unique because I don't really can give a cause then.
Maybe the Discord API had a high ping at that moment or something and so it couldn't process the information properly.

**Comment by Veltimo** [comment]
As far as I know all the permissions of the bot are complete, it's a strange situation but I don't think I'll ever live
