### ISSUE TITLE
Suggestion: Message Collecting Giveaway Steps

### ISSUE THREAD

**Issue by KrabbyBuckets** [Androz2091/discord-giveaways#143]
I really tried using the .on('collect') event but i really dont know how.

if yalls could add this this will be great

**Comment by NicoHd105** [comment]
"Could add this". You hopefully understood that this is a package/module and not a bot. If you do it properly you can add message collection easily, I even used awaitMessages and collect together. That is just Discord.js coding, nothing that this module would need to provide because it does not have to so with the giveaway system itself, just providing it's options. If you really are struggling go and ask for help in the official Discord.js support server, you can find a link on the docs or github page of it. Now please close this issue.
