### ISSUE TITLE
Weird MongoDB Database error

### ISSUE THREAD

**Issue by Aktindo** [Androz2091/discord-giveaways#200]
See below

**Comment by Aktindo** [comment]
Also I am getting this error
`VersionError: No matching document found for id "6013940ba1c5f03408d2415d" version 5 modifiedPaths "data"`

**Comment by Nico105** [comment]
Are you using quickmongo as the DB?

**Comment by Aktindo** [comment]
I am using both mongoose and quickmongo

**Comment by Aktindo** [comment]
Like normally I use mongoose, but for this package i am using quickmongo

**Comment by Nico105** [comment]
Yeah, the error is because of quickmongo messing things up/not doing good enough with the speed of data saving and getting it, I will try to figure smth out to make it better.
Because you talked about using `mongoose` normally, I guess you didn't see the example on the ` develop` branch yet did you? Because if you like you can use that one because it does not have the error.

**Comment by Aktindo** [comment]
Oh I see it now. I guess I will check the mongoose example on the develop branch and see if it fixes the error.

**Comment by Nico105** [comment]
It does, as said it's because of quickmongo, not mongoDB itself.

**Comment by Aktindo** [comment]
Yup, it seems to have fixed the issue.
