### ISSUE TITLE
mongoDB (quickmongo) err

### ISSUE THREAD

**Issue by Ult1m1** [Androz2091/discord-giveaways#248]
npm v. 4.4.3
djs v12
node v12
win 10

Main File: https://sourceb.in/FDpvAlYq7w
ERR: https://sourceb.in/PgPt5WeOyH
Giveaway cmd: https://sourceb.in/rVLJzA7U1H

**Comment by Nico105** [comment]
It's because it's not `db.once` but `db.on` in your main file, it will get changed with the next release.
 
https://github.com/Androz2091/discord-giveaways/blob/develop/examples/custom-databases/quickmongo.js
I recommend you use the unreleased version of the example, you only have to take note to add the line 65 and 70 part

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
