### ISSUE TITLE
Error: EROFS: read-only file system, open ‘../../giveaways.json’

### ISSUE THREAD

**Issue by AdamTmHun** [Androz2091/discord-giveaways#260]
![E96A721B-57B8-4847-806C-F76D3D6A7FFF](https://user-images.githubusercontent.com/61880960/114611088-ee33ba80-9ca0-11eb-9a2a-c85a223324fc.jpeg)

I get this error when starting on vps/repl.it. On my pc, I have never gotten such an error.

Can anyone help me how to fix this?

**Comment by Nico105** [comment]
If you are sharding you need to use https://github.com/Androz2091/discord-giveaways#support-shards _idk if that's the real issue_
and if you mainly host your bot on replit then you should switch to [mongoDB or their own replit DB](https://github.com/Androz2091/discord-giveaways/tree/develop/examples/custom-databases) because .json is not safe on replit
try just adding the sharding support first and then report back okay?

**Comment by AdamTmHun** [comment]
Alright. I have got the extended manager class via the sharding support, and I have private repl via hacker plan so it shouldn't really bae unsafe. But let me try what you suggested.

**Comment by AdamTmHun** [comment]
Here's the extended Discord.js client in case I did something wrong in that:
https://sourceb.in/o6q2xwpBem

**Comment by Nico105** [comment]
looks fine, you only have a bit more [default manager options](https://discord-giveaways.js.org/global.html#GiveawaysManagerOptions) than there really exist, the messages and stuff go into the [.start() options](https://github.com/Androz2091/discord-giveaways#-translation)

but idk does replit have some kind of settings for the file system or smth because the error suggests that it got made read only...

**Comment by AdamTmHun** [comment]
Alright, I will try to use quickdb then ig, since I have mongo free plan rn and I don't want the cluster be filled with already ended giveaways 😅

**Comment by AdamTmHun** [comment]
I will close this if I succeed

**Comment by Nico105** [comment]
> Alright, I will try to use quickdb then ig, since I have mongo free plan rn and I don't want the cluster be filled with already ended giveaways 😅

k, we have a `endedGiveawaysLifeTime` tho which would delete them after a new start
and for quick.db idk yet 100% if it is persistent, so when you experience giveaway data resets = 2 endings then you have to use the replit DB or mongo

**Comment by AdamTmHun** [comment]
Alright.

Also got some typeErrors via typescript, when creating  `new GiveawayManager`, and setting `options.storage` to `false`, as the example said.

**Comment by Nico105** [comment]
yeah sry, that will get removed with the next release, just remove the `storage` property, that's what should be done

**Comment by AdamTmHun** [comment]
Alright, thanks for the help.

**Comment by Dragonizedpizza** [comment]
Also, I'm gonna assume since you're on repl.it, ../../giveaways.json is one - or 2 - ../ many.
if you do too many ../, you end up going outside the allocated directory for you on repl.it.
