### ISSUE TITLE
Giveaway not ending.

### ISSUE THREAD

**Issue by DeathMario** [Androz2091/discord-giveaways#300]
![20210603_153835](https://user-images.githubusercontent.com/69960734/120663655-1e6a2f00-c482-11eb-8cad-7a0da9c2130c.png)

**Describe the bug**  

When I end a giveaway with the Giveaway End Command or when a giveaway is ended. It will start again for the reaming countdown when ending it after 1-2 hours and says new winners to the cooldown end
**Error**  

A screenshot or the text block of the error if there is one.

**To Reproduce**  
Start a giveaway for duration +1day or end one

**Expected behavior**  

It will stop the giveaway and not starting more
**Screenshots**  

**Additional context**

* `discord-giveaways` version: Lastest 4.5.1
* `discord.js` version: Lastest 12^
* Custom Database (if you use one): Quick.db (i tried mongo and same )

**Comment by DeathMario** [comment]
As you can see, the gend command was executed yesterday and the embed timestamp says ended today, yesterday happens the same.

**Comment by Nico105** [comment]
I assumr you used mongod cloud cluster so it should be irrelevant, but where do you host your bot?

**Comment by DeathMario** [comment]
> I assume you used mongos cloud cluster so it should be irrelevant, but just to confirm, where do you host your bot?

on replit

**Comment by Nico105** [comment]
local stored data on replit [does not really work](https://github.com/Androz2091/discord-giveaways/issues/228#issuecomment-805779193), so as far as I know quick.db included. We had such "giveaway resets on it's own" problems before because of that.
But the weird thing is that you said it happend with mongoDB too, which should not be possible since it's in the cloud.
Are you sure you used `new GiveawaysManagerWithOwnDatabase` to create your manager? (I just mean if you really used your extended class)

**Comment by DeathMario** [comment]
> local stored data on replit [does not really work](https://github.com/Androz2091/discord-giveaways/issues/228#issuecomment-805779193), so as far as I know quick.db included. We had such "giveaway resets on it's own" problems before because of that.
> But the weird thing is that you said it happend with mongoDB too, which should not be possible since it's in the cloud.
> Are you sure you used `new GiveawaysManagerWithOwnDatabase` to create your manager? (I just mean if you really used your extended class)

Anyway thanks, i thin i did something wrong with mongo, im gonna close issue
