### ISSUE TITLE
Stop failed reroll message, customize end message as a Message

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#431]
Firstly, when I reroll a giveaway and there aren't enough participants, this message is sent in the chat.
![image](https://user-images.githubusercontent.com/70718540/151909468-9012f4a2-5bc9-40d7-8c2b-9cffee6ba95f.png)
Can I stop this from happening?

Secondly, can I modify the giveaway end message as a Message? Like add components to it.

**Comment by Dragonizedpizza** [comment]
...?

**Comment by Nico105** [comment]
I will add an option.
and #422

**Comment by Dragonizedpizza** [comment]
> Can I stop this from happening?

By this I meant that I wanted to make it an ephemeral, or get an error thrown.

So what you could do is add an option called noFailedReroll message in GiveawayManager

**Comment by imranbarbhuiya** [comment]
> > Can I stop this from happening?
> 
> By this I meant that I wanted to make it an ephemeral, or get an error thrown.
> 
> So what you could do is add an option called noFailedRerollMessage in GiveawayManager

Throwing an error will be good so we can catch it and show ephemeral message. But I think it'll make it a samver:major. So Instead of `noFailedRerollMessage` add a option for `failOnNoWinner` or anything other name idc and if this reroll option is true then Instead of sending a message reject the promise.

**Comment by Dragonizedpizza** [comment]
It can be closed, thank you very much.
